# Generated by Django 4.2.1 on 2023-08-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='sent_to',
            new_name='send_to',
        ),
    ]
